version: '3'

services:
  db:
    image: bitnami/mysql:latest
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/bitnami/mysql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      # ALLOW_EMPTY_PASSWORD: 'no'
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'dbms'
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: 'EFRS'
      # MYSQL_ROOT_USER: 'root'
      # MYSQL_ROOT_PASSWORD: 'ZFhLrUg1QV9FzUy4x8RT'
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  #   environment:
  #     DB_PORT: 3309
  #   links:
  #     - "db"
  #   depends_on:
  #     - db  

